# Generated by Django 5.0.7 on 2024-07-29 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note_attachment',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='notes.notes'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='title',
            field=models.TextField(),
        ),
    ]
